version: "3"

services:
  billing:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
    - "$PWD:$PWD"
    working_dir: "$PWD"
    command:
    - /bin/bash
    - -c
    - |
      make upgrade_db &&
      cd ./tests &&
      python3 -m pytest --junitxml=report.xml --cov-report=xml --cov=.
    environment:
      PYTHONDONTWRITEBYTECODE: 1
      POSTGRES_PASSWORD: postgres
      POSTGRES_SERVER: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      SERVER_HOST: 0.0.0.0
      SERVER_PORT: 8000
      PROJECT_NAME: billing
    depends_on:
    - db

  db:
    image: postgres
    ports:
      - 5454:5432
    environment:
      POSTGRES_PASSWORD: postgres
#    logging:
#      driver: "none"
